### ISSUE TITLE
Broken link to examples

### ISSUE THREAD

**Issue by Don42** [ferrous-systems/mdslides#16]
When looking for examples of how this is used I noticed that the link is either broken or points to a private repository as github shows the 404 page.

The link: https://github.com/ferrous-systems/material-templates

**Comment by jonathanpallant** [comment]
Ah, thank you! https://github.com/ferrous-systems/rust-training is a public example. I'll fix the link.

**Comment by Don42** [comment]
BTW, the link in the [rust-training README](https://github.com/ferrous-systems/rust-training) also points to the rust-exercises releases (which don't contain the slides). This also seems like a link error.

**Comment by jonathanpallant** [comment]
Yes, that's a typo. Thank you!

**Comment by jonathanpallant** [comment]
PR's opened.
